package edu.brook.sugarscape;

/**
 * Sugar Cell Java Implementation.
 *  history 19990624 AAL changed variables from private to protected so SpiceCell could inherit seperated peak creation from initialize() history 19990629 AAL removed a variety of "sugar"related methods and          attributes, and put them in new class CommoditySource
 * Generated by metaabm system: Sep 16, 2009 7:25:02 PM PDT in project: org.eclipse.amp.amf.examples.ascape  */

public class SugarCell extends org.ascape.model.HostCell {

	/**
	 * 
	 */

	private double perceivedValue = 0.0;
	/**
	 * 
	 */

	private double sugarAmount = 0.0;
	/**
	 * Constructs a new Sugar Cell.
	 */

	public SugarCell() {
		createUniqueID();
	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes
	private static final long serialVersionUID = 89989998L;

	private String uniqueID;

	public String getUID() {
		return uniqueID;
	}

	public void createUniqueID() {
		//uniqueID = org.apache.commons.lang.RandomStringUtils.randomAlphanumeric(5);
	}

	/**
	 * Clones the agent, ensuring that a unique id is assigned.
	 */
	public Object clone() {
		try {
			SugarCell clone = (SugarCell) super.clone();
			clone.createUniqueID();
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	public GAS_Base getGAS_Base() {
		return (GAS_Base) getScape().getRoot();
	}

	public java.awt.Color getColor() {
		return java.awt.Color.LIGHT_GRAY;
	}
	/**
	 * .
	 */

	public void sugarGrowBack1() {

	}
	/**
	 * .
	 */

	public void sugarGrowBackEpsilon() {

	}
	/**
	 * .
	 */

	public void intializeNonFramework() {

	}

	/**
	 * Gets the Perceived Value property for Sugar Cell.
	 * @return 
	 */

	public double getPerceivedValue() {
		return perceivedValue;
	}

	/**
	 * Sets the Perceived Value property for Sugar Cell.
	 * 
	 * @param _perceivedValue the new Perceived Value value
	 */

	public void setPerceivedValue(double _perceivedValue) {
		perceivedValue = _perceivedValue;
	}
	/**
	 * Gets the Sugar Amount property for Sugar Cell.
	 * @return 
	 */

	public double getSugarAmount() {
		return sugarAmount;
	}

	/**
	 * Sets the Sugar Amount property for Sugar Cell.
	 * 
	 * @param _sugarAmount the new Sugar Amount value
	 */

	public void setSugarAmount(double _sugarAmount) {
		sugarAmount = _sugarAmount;
	}

	public String getName() {
		if (name == null) {
			return "Sugar Cell " + uniqueID;
		} else {
			return name;
		}
	}
}
