/*
* generated by Xtext
*/
package org.eclipse.amp.amf.abase.ui.contentassist;

import org.eclipse.amp.amf.abase.ui.contentassist.AbstractABaseProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ABaseProposalProvider extends AbstractABaseProposalProvider {

}
