/*
* generated by Xtext
*/

package org.eclipse.amp.amf.parameters.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.amp.amf.abase.services.ABaseGrammarAccess;

@Singleton
public class AParGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cModelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cModelImportParserRuleCall_2_0 = (RuleCall)cModelAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIncorporatesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIncorporatesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIncorporatesIncorporatesParserRuleCall_3_1_0 = (RuleCall)cIncorporatesAssignment_3_1.eContents().get(0);
		private final Assignment cParametersAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cParametersParameterParserRuleCall_4_0 = (RuleCall)cParametersAssignment_4.eContents().get(0);
		
		//Model:
		//	name=STRING? "model" model=Import ("incorporates" incorporates+=Incorporates)* parameters+=Parameter*;
		public ParserRule getRule() { return rule; }

		//name=STRING? "model" model=Import ("incorporates" incorporates+=Incorporates)* parameters+=Parameter*
		public Group getGroup() { return cGroup; }

		//name=STRING?
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0_0() { return cNameSTRINGTerminalRuleCall_0_0; }

		//"model"
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }

		//model=Import
		public Assignment getModelAssignment_2() { return cModelAssignment_2; }

		//Import
		public RuleCall getModelImportParserRuleCall_2_0() { return cModelImportParserRuleCall_2_0; }

		//("incorporates" incorporates+=Incorporates)*
		public Group getGroup_3() { return cGroup_3; }

		//"incorporates"
		public Keyword getIncorporatesKeyword_3_0() { return cIncorporatesKeyword_3_0; }

		//incorporates+=Incorporates
		public Assignment getIncorporatesAssignment_3_1() { return cIncorporatesAssignment_3_1; }

		//Incorporates
		public RuleCall getIncorporatesIncorporatesParserRuleCall_3_1_0() { return cIncorporatesIncorporatesParserRuleCall_3_1_0; }

		//parameters+=Parameter*
		public Assignment getParametersAssignment_4() { return cParametersAssignment_4; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_4_0() { return cParametersParameterParserRuleCall_4_0; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Assignment cImportURIAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_0 = (RuleCall)cImportURIAssignment.eContents().get(0);
		
		//Import:
		//	importURI=STRING;
		public ParserRule getRule() { return rule; }

		//importURI=STRING
		public Assignment getImportURIAssignment() { return cImportURIAssignment; }

		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_0() { return cImportURISTRINGTerminalRuleCall_0; }
	}

	public class IncorporatesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Incorporates");
		private final Assignment cImportURIAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_0 = (RuleCall)cImportURIAssignment.eContents().get(0);
		
		//Incorporates:
		//	importURI=STRING;
		public ParserRule getRule() { return rule; }

		//importURI=STRING
		public Assignment getImportURIAssignment() { return cImportURIAssignment; }

		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_0() { return cImportURISTRINGTerminalRuleCall_0; }
	}

	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Parameter");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSingleParameterParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSweepParameterParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSweepLinkParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Parameter:
		//	SingleParameter | SweepParameter | SweepLink;
		public ParserRule getRule() { return rule; }

		//SingleParameter | SweepParameter | SweepLink
		public Alternatives getAlternatives() { return cAlternatives; }

		//SingleParameter
		public RuleCall getSingleParameterParserRuleCall_0() { return cSingleParameterParserRuleCall_0; }

		//SweepParameter
		public RuleCall getSweepParameterParserRuleCall_1() { return cSweepParameterParserRuleCall_1; }

		//SweepLink
		public RuleCall getSweepLinkParserRuleCall_2() { return cSweepLinkParserRuleCall_2; }
	}

	public class SingleParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SingleParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAttributeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cAttributeSAttributeCrossReference_0_0 = (CrossReference)cAttributeAssignment_0.eContents().get(0);
		private final RuleCall cAttributeSAttributeIDTerminalRuleCall_0_0_1 = (RuleCall)cAttributeSAttributeCrossReference_0_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//SingleParameter:
		//	attribute=[SAttribute] "=" value=Value;
		public ParserRule getRule() { return rule; }

		//attribute=[SAttribute] "=" value=Value
		public Group getGroup() { return cGroup; }

		//attribute=[SAttribute]
		public Assignment getAttributeAssignment_0() { return cAttributeAssignment_0; }

		//[SAttribute]
		public CrossReference getAttributeSAttributeCrossReference_0_0() { return cAttributeSAttributeCrossReference_0_0; }

		//ID
		public RuleCall getAttributeSAttributeIDTerminalRuleCall_0_0_1() { return cAttributeSAttributeIDTerminalRuleCall_0_0_1; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=Value
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//Value
		public RuleCall getValueValueParserRuleCall_2_0() { return cValueValueParserRuleCall_2_0; }
	}

	public class SweepParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SweepParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAttributeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cAttributeSAttributeCrossReference_0_0 = (CrossReference)cAttributeAssignment_0.eContents().get(0);
		private final RuleCall cAttributeSAttributeIDTerminalRuleCall_0_0_1 = (RuleCall)cAttributeSAttributeCrossReference_0_0.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStartValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStartValueValueParserRuleCall_2_0 = (RuleCall)cStartValueAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEndValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEndValueValueParserRuleCall_4_0 = (RuleCall)cEndValueAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cIncrementAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cIncrementValueParserRuleCall_6_0 = (RuleCall)cIncrementAssignment_6.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//SweepParameter:
		//	attribute=[SAttribute] "[" startValue=Value "," endValue=Value "," increment=Value "]";
		public ParserRule getRule() { return rule; }

		//attribute=[SAttribute] "[" startValue=Value "," endValue=Value "," increment=Value "]"
		public Group getGroup() { return cGroup; }

		//attribute=[SAttribute]
		public Assignment getAttributeAssignment_0() { return cAttributeAssignment_0; }

		//[SAttribute]
		public CrossReference getAttributeSAttributeCrossReference_0_0() { return cAttributeSAttributeCrossReference_0_0; }

		//ID
		public RuleCall getAttributeSAttributeIDTerminalRuleCall_0_0_1() { return cAttributeSAttributeIDTerminalRuleCall_0_0_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }

		//startValue=Value
		public Assignment getStartValueAssignment_2() { return cStartValueAssignment_2; }

		//Value
		public RuleCall getStartValueValueParserRuleCall_2_0() { return cStartValueValueParserRuleCall_2_0; }

		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }

		//endValue=Value
		public Assignment getEndValueAssignment_4() { return cEndValueAssignment_4; }

		//Value
		public RuleCall getEndValueValueParserRuleCall_4_0() { return cEndValueValueParserRuleCall_4_0; }

		//","
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }

		//increment=Value
		public Assignment getIncrementAssignment_6() { return cIncrementAssignment_6; }

		//Value
		public RuleCall getIncrementValueParserRuleCall_6_0() { return cIncrementValueParserRuleCall_6_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_7() { return cRightSquareBracketKeyword_7; }
	}

	public class SweepLinkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SweepLink");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSweepLinkAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cParametersAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_2_0 = (RuleCall)cParametersAssignment_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//SweepLink:
		//	{SweepLink} "[" parameters+=Parameter* "]";
		public ParserRule getRule() { return rule; }

		//{SweepLink} "[" parameters+=Parameter* "]"
		public Group getGroup() { return cGroup; }

		//{SweepLink}
		public Action getSweepLinkAction_0() { return cSweepLinkAction_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }

		//parameters+=Parameter*
		public Assignment getParametersAssignment_2() { return cParametersAssignment_2; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_2_0() { return cParametersParameterParserRuleCall_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	
	
	private ModelElements pModel;
	private ImportElements pImport;
	private IncorporatesElements pIncorporates;
	private ParameterElements pParameter;
	private SingleParameterElements pSingleParameter;
	private SweepParameterElements pSweepParameter;
	private SweepLinkElements pSweepLink;
	
	private final GrammarProvider grammarProvider;

	private ABaseGrammarAccess gaABase;

	@Inject
	public AParGrammarAccess(GrammarProvider grammarProvider,
		ABaseGrammarAccess gaABase) {
		this.grammarProvider = grammarProvider;
		this.gaABase = gaABase;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public ABaseGrammarAccess getABaseGrammarAccess() {
		return gaABase;
	}

	
	//Model:
	//	name=STRING? "model" model=Import ("incorporates" incorporates+=Incorporates)* parameters+=Parameter*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Import:
	//	importURI=STRING;
	public ImportElements getImportAccess() {
		return (pImport != null) ? pImport : (pImport = new ImportElements());
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//Incorporates:
	//	importURI=STRING;
	public IncorporatesElements getIncorporatesAccess() {
		return (pIncorporates != null) ? pIncorporates : (pIncorporates = new IncorporatesElements());
	}
	
	public ParserRule getIncorporatesRule() {
		return getIncorporatesAccess().getRule();
	}

	//Parameter:
	//	SingleParameter | SweepParameter | SweepLink;
	public ParameterElements getParameterAccess() {
		return (pParameter != null) ? pParameter : (pParameter = new ParameterElements());
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//SingleParameter:
	//	attribute=[SAttribute] "=" value=Value;
	public SingleParameterElements getSingleParameterAccess() {
		return (pSingleParameter != null) ? pSingleParameter : (pSingleParameter = new SingleParameterElements());
	}
	
	public ParserRule getSingleParameterRule() {
		return getSingleParameterAccess().getRule();
	}

	//SweepParameter:
	//	attribute=[SAttribute] "[" startValue=Value "," endValue=Value "," increment=Value "]";
	public SweepParameterElements getSweepParameterAccess() {
		return (pSweepParameter != null) ? pSweepParameter : (pSweepParameter = new SweepParameterElements());
	}
	
	public ParserRule getSweepParameterRule() {
		return getSweepParameterAccess().getRule();
	}

	//SweepLink:
	//	{SweepLink} "[" parameters+=Parameter* "]";
	public SweepLinkElements getSweepLinkAccess() {
		return (pSweepLink != null) ? pSweepLink : (pSweepLink = new SweepLinkElements());
	}
	
	public ParserRule getSweepLinkRule() {
		return getSweepLinkAccess().getRule();
	}

	//Value:
	//	IntValue | StringValue | RealValue | BooleanValue;
	public ABaseGrammarAccess.ValueElements getValueAccess() {
		return gaABase.getValueAccess();
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}

	//IntValue:
	//	value=INTEGER;
	public ABaseGrammarAccess.IntValueElements getIntValueAccess() {
		return gaABase.getIntValueAccess();
	}
	
	public ParserRule getIntValueRule() {
		return getIntValueAccess().getRule();
	}

	//RealValue:
	//	value=REAL;
	public ABaseGrammarAccess.RealValueElements getRealValueAccess() {
		return gaABase.getRealValueAccess();
	}
	
	public ParserRule getRealValueRule() {
		return getRealValueAccess().getRule();
	}

	//StringValue:
	//	value=STRING;
	public ABaseGrammarAccess.StringValueElements getStringValueAccess() {
		return gaABase.getStringValueAccess();
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}

	//BooleanValue:
	//	value=BOOLEAN;
	public ABaseGrammarAccess.BooleanValueElements getBooleanValueAccess() {
		return gaABase.getBooleanValueAccess();
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}

	//enum BOOLEAN:
	//	TRUE="true" | FALSE="false";
	public ABaseGrammarAccess.BOOLEANElements getBOOLEANAccess() {
		return gaABase.getBOOLEANAccess();
	}
	
	public EnumRule getBOOLEANRule() {
		return getBOOLEANAccess().getRule();
	}

	//terminal INTEGER:
	//	"-"? "0".."9"+;
	public TerminalRule getINTEGERRule() {
		return gaABase.getINTEGERRule();
	} 

	//terminal REAL:
	//	"-"? "0".."9"* "." "0".."9"*;
	public TerminalRule getREALRule() {
		return gaABase.getREALRule();
	} 

	//terminal DESC_STRING:
	//	"«" ("\\" ("b" | "t" | "n" | "f" | "r" | "«" | "»" | "\\") | !("\\" | "«" | "»"))* "»";
	public TerminalRule getDESC_STRINGRule() {
		return gaABase.getDESC_STRINGRule();
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaABase.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaABase.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaABase.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaABase.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaABase.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaABase.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaABase.getANY_OTHERRule();
	} 
}
