/**
 * <copyright>
 *
 * Copyright (c) 2007-2009 Metascape, LLC
 * Copyright (c) 2006-2007 Argonne National Labs
 * All rights reserved.   This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *   Argonne National Laboratory - Initial development (pre-contribution)
 *   Metascape - Subsequent development and maintenance
 *
 * </copyright>
 */
package org.metaabm.act.validation;

import org.metaabm.IValue;
import org.metaabm.act.ALiteral;
import org.metaabm.act.ASelect;
import org.metaabm.act.ASink;

/**
 * A sample validator interface for {@link org.metaabm.act.AInput}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AInputValidator {
	boolean validate();

	boolean validateSink(ASink value);

	boolean validateSelected(ASelect value);

	boolean validateLiteral(ALiteral value);

	boolean validateValue(IValue value);
}
