package edu.brook;

/**
 * Play Cell Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Nov 2, 2009 8:54:43 PM PST in project: org.eclipse.amp.amf.examples.repast  */

public class PlayCellStyle
		extends
			repast.simphony.visualization.visualization2D.style.DefaultStyle2D {

	public static final java.awt.Shape SHAPE_OVAL = new java.awt.geom.Ellipse2D.Double(
			0, 0, 10, 10);
	public static final java.awt.Shape SHAPE_RECT = new java.awt.geom.Rectangle2D.Double(
			0, 0, 10, 10);
	public static final java.awt.Shape SHAPE_MARKER = new java.awt.geom.Rectangle2D.Double(
			0, 0, 5, 5);

	java.awt.Shape shape = SHAPE_RECT;

	public void updateValues(Object object) {

		PlayCell playCellRule = (PlayCell) object;

		java.awt.Color playCellRuleColorGreen = java.awt.Color.GREEN

		;

		setPaint(playCellRuleColorGreen);

		java.awt.Shape playCellRuleShapeRectangle = SHAPE_RECT;

		shape = playCellRuleShapeRectangle;

	}
	public edu.umd.cs.piccolo.PNode getPNode(Object object,
			edu.umd.cs.piccolo.PNode node) {
		updateValues(object);
		edu.umd.cs.piccolo.nodes.PPath path = new edu.umd.cs.piccolo.nodes.PPath(
				shape);
		path.setBounds(getBounds(object));
		return path;
	}
	public java.awt.Paint getPaint(Object object) {
		updateValues(object);
		return super.getPaint(object);
	}
}
