package org.metaabm.examples.stupid1;

/**
 * Bug Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Nov 2, 2009 8:54:42 PM PST in project: org.eclipse.amp.amf.examples.repast  */

public class BugStyle2D
		extends
			repast.simphony.visualization.visualization2D.style.DefaultStyle2D {

	public static final java.awt.Shape SHAPE_OVAL = new java.awt.geom.Ellipse2D.Double(
			0, 0, 10, 10);
	public static final java.awt.Shape SHAPE_RECT = new java.awt.geom.Rectangle2D.Double(
			0, 0, 10, 10);
	public static final java.awt.Shape SHAPE_MARKER = new java.awt.geom.Rectangle2D.Double(
			0, 0, 5, 5);

	java.awt.Shape shape = SHAPE_RECT;

	public void updateValues(Object object) {

		setBounds(new java.awt.Rectangle(0, 0, 9, 9));

		Bug bugRule = (Bug) object;

		java.awt.Color bugRuleColorRed = java.awt.Color.RED

		;

		setPaint(bugRuleColorRed);

		java.awt.Shape bugRuleShapeOval = SHAPE_OVAL;

		shape = bugRuleShapeOval;

	}
	public edu.umd.cs.piccolo.PNode getPNode(Object object,
			edu.umd.cs.piccolo.PNode node) {
		updateValues(object);
		edu.umd.cs.piccolo.nodes.PPath path = new edu.umd.cs.piccolo.nodes.PPath(
				shape);
		path.setBounds(getBounds(object));
		return path;
	}
	public java.awt.Paint getPaint(Object object) {
		updateValues(object);
		return super.getPaint(object);
	}
}
