/*
* generated by Xtext
*/
package org.eclipse.amp.amf.abase.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.amp.amf.abase.services.ABaseGrammarAccess;

public class ABaseParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ABaseGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.amp.amf.abase.parser.antlr.internal.InternalABaseParser createParser(XtextTokenStream stream) {
		return new org.eclipse.amp.amf.abase.parser.antlr.internal.InternalABaseParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Value";
	}
	
	public ABaseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ABaseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
