/*
 * generated by Xtext
 */
package org.eclipse.amp.amf.abase.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ABaseExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.eclipse.amp.amf.abase.ui.internal.ABaseActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.eclipse.amp.amf.abase.ui.internal.ABaseActivator.getInstance().getInjector("org.eclipse.amp.amf.abase.ABase");
	}
	
}
