package edu.brook;

/**
 * Cooperate Defect Style Java Implementation.
 * 
 * Generated by metaabm system: Nov 18, 2008 11:59:45 PM PST in project: org.metaabm.examples.ascape  */

public interface ICooperateDefectStyle {

}
