/**
 * <copyright>
 * </copyright>
 *
 * $Id: RunSetValidator.java,v 1.2 2010/08/04 01:54:47 mparker Exp $
 */
package org.eclipse.amp.amf.testing.ares.validation;

import java.util.Date;

import org.eclipse.amp.amf.testing.ares.ResultType;
import org.eclipse.amp.amf.testing.ares.Run;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.amp.amf.testing.ares.RunSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RunSetValidator {
    boolean validate();

    boolean validateResult(ResultType value);
    boolean validateStarted(Date value);
    boolean validateFinished(Date value);
    boolean validateRuns(EList<Run> value);
}
