package name.milesparker.epi;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import org.ascape.util.vis.DrawFeature;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

/**
 * <!-- begin-user-doc -->
 * Individual Style 2D Java Implementation.
 * 
 * Generated by AMF for model: Epidemic.metaabm in project: org.eclipse.amp.amf.examples.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class IndividualStyle2D extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {
		Shape shape = null;
		HostCell rootActGroupCell = (HostCell) object;
		if (rootActGroupCell.getOccupant() instanceof Individual) {
			Individual rootActGroup = (Individual) rootActGroupCell
					.getOccupant();
			Individual individualRule = rootActGroup;
			if (individualRule.getStatus() == StatusEnum.susceptible) {
				java.awt.Color individualRuleColorBlue = java.awt.Color.BLUE

				;

				g.setColor(individualRuleColorBlue);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
			}
			if (individualRule.getStatus() == StatusEnum.exposed) {
				java.awt.Color individualRuleColorYellow = java.awt.Color.YELLOW

				;

				g.setColor(individualRuleColorYellow);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
			}
			if (individualRule.getStatus() == StatusEnum.asymptomInfectious) {
				java.awt.Color individualRuleColorOrange = java.awt.Color.ORANGE

				;

				g.setColor(individualRuleColorOrange);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
			}
			if (individualRule.getStatus() == StatusEnum.recovered) {
				java.awt.Color individualRuleColorGreen = java.awt.Color.GREEN

				;

				g.setColor(individualRuleColorGreen);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
			}
			if (individualRule.getStatus() == StatusEnum.dead) {
				java.awt.Color individualRuleColorBlack = java.awt.Color.BLACK

				;

				g.setColor(individualRuleColorBlack);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
			}
			if (individualRule.getStatus() == StatusEnum.symptomInfectious) {
				java.awt.Color individualRuleColorRed = java.awt.Color.RED

				;

				g.setColor(individualRuleColorRed);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
			}
		}
	}
}
