package edu.brook;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import org.ascape.util.vis.DrawFeature;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

/**
 * <!-- begin-user-doc -->
 * Cooperate Defect Style Java Implementation.
 * 
 * Generated by AMF for model: DemographicPrisoner_sDilemma.metaabm in project: org.eclipse.amp.amf.examples.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class CooperateDefectStyle extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {
		Shape shape = null;
		HostCell rootActGroupCell = (HostCell) object;
		if (rootActGroupCell.getOccupant() instanceof Player) {
			Player rootActGroup = (Player) rootActGroupCell.getOccupant();
			Player playerRule = rootActGroup;
			if (playerRule.isCooperate()) {
				java.awt.Color playerRuleColorBlue = java.awt.Color.BLUE

				;

				g.setColor(playerRuleColorBlue);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
			}
			if (!(playerRule.isCooperate())) {
				java.awt.Color playerRuleColorRed = java.awt.Color.RED

				;

				g.setColor(playerRuleColorRed);
				shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
				((Graphics2D) g).fill(shape);
			}
		}
	}
}
