/*
* generated by Xtext
*/
package org.eclipse.amp.amf.testing.ui.contentassist;

import org.eclipse.amp.amf.testing.ui.contentassist.AbstractATestProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ATestProposalProvider extends AbstractATestProposalProvider {

}
