package org.metaabm.examples.stupid2;

/**
 * Bug Style 2D Java Implementation.
 * 
 * Generated by metaabm system: Nov 2, 2009 8:54:41 PM PST in project: org.eclipse.amp.amf.examples.repast  */

public class BugStyle2D
		extends
			repast.simphony.visualization.visualization2D.style.DefaultStyle2D {

	public static final java.awt.Shape SHAPE_OVAL = new java.awt.geom.Ellipse2D.Double(
			0, 0, 10, 10);
	public static final java.awt.Shape SHAPE_RECT = new java.awt.geom.Rectangle2D.Double(
			0, 0, 10, 10);
	public static final java.awt.Shape SHAPE_MARKER = new java.awt.geom.Rectangle2D.Double(
			0, 0, 5, 5);

	java.awt.Shape shape = SHAPE_RECT;

	public void updateValues(Object object) {

		setBounds(new java.awt.Rectangle(0, 0, 9, 9));

		Bug bugRule = (Bug) object;

		double bugSizeRatio = bugRule.getSize() / 10.0;

		double bugSizeUnit = java.lang.Math.min(bugSizeRatio, 1.0)

		;

		double invertBugSize = 1 - bugSizeUnit;

		java.awt.Color bugRuleColorRGB_BugRuleMinimum_BugSizeRatioLiteral1pt0_Literal1pt0Literal1pt0_ = new java.awt.Color(
				(float) 1.0, (float) invertBugSize, (float) invertBugSize)

		;

		setPaint(bugRuleColorRGB_BugRuleMinimum_BugSizeRatioLiteral1pt0_Literal1pt0Literal1pt0_);

		java.awt.Shape bugRuleShapeOval = SHAPE_OVAL;

		shape = bugRuleShapeOval;

	}
	public edu.umd.cs.piccolo.PNode getPNode(Object object,
			edu.umd.cs.piccolo.PNode node) {
		updateValues(object);
		edu.umd.cs.piccolo.nodes.PPath path = new edu.umd.cs.piccolo.nodes.PPath(
				shape);
		path.setBounds(getBounds(object));
		return path;
	}
	public java.awt.Paint getPaint(Object object) {
		updateValues(object);
		return super.getPaint(object);
	}
}
