package org.metaabm.examples.stupid1;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import org.ascape.util.vis.DrawFeature;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

/**
 * <!-- begin-user-doc -->
 * Bug Style 2D Java Implementation.
 * 
 * Generated by AMF for model: StupidModel1.metaabm in project: org.eclipse.amp.amf.examples.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class BugStyle2D extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {
		Shape shape = null;
		HostCell rootActGroupCell = (HostCell) object;
		if (rootActGroupCell.getOccupant() instanceof Bug) {
			Bug rootActGroup = (Bug) rootActGroupCell.getOccupant();
			Bug bugRule = rootActGroup;
			java.awt.Color bugRuleColorRed = java.awt.Color.RED

			;

			g.setColor(bugRuleColorRed);
			shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
			((Graphics2D) g).fill(shape);
		}
	}
}
