package org.eclipse.amp.amf.examples.escape;

/**
 * Block Java Implementation.
 * 
 * Generated by metaabm system: Nov 2, 2009 8:54:39 PM PST in project: org.eclipse.amp.amf.examples.repast  */

public class Block {

	/**
	 * Constructs a new Block.
	 */

	public Block() {
		createUniqueID();
	}

	//todo, make this a useful value for evaluating compatibility of different versions of generated classes
	private static final long serialVersionUID = 89989998L;

	private String uniqueID;

	public String getUID() {
		return uniqueID;
	}

	public void createUniqueID() {
		//uniqueID = org.apache.commons.lang.RandomStringUtils.randomAlphanumeric(5);
	}

	/**
	 * Clones the agent, ensuring that a unique id is assigned.
	 */
	public Object clone() {
		try {
			Block clone = (Block) super.clone();
			clone.createUniqueID();
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	/**
	 * 
	 */

	private WikiExample wikiExampleList = null;

	/**
	 * Gets the WikiExample property for .
	 * @return 
	 */

	public WikiExample getWikiExample() {
		return wikiExampleList;
	}

	/**
	 * Sets the WikiExample property for .
	 * 
	 * @param _wikiExample the new WikiExample value
	 */

	public void setWikiExample(WikiExample _wikiExample) {
		wikiExampleList = _wikiExample;
	}

	public double randomInRange(double minValue, double maxValue) {
		return repast.simphony.random.RandomHelper.nextDoubleFromTo(minValue,
				maxValue);
	}

	public double randomToLimit(double maxValue) {
		return repast.simphony.random.RandomHelper.nextDoubleFromTo(0.0,
				maxValue);
	}

	public int randomToLimit(int maxValue) {
		return repast.simphony.random.RandomHelper.nextIntFromTo(0, maxValue);
	}
}
