/*
 * generated by Xtext
 */
package org.eclipse.amp.amf.testing;

import org.eclipse.amp.amf.testing.scoping.ATestImportResolver;
import org.eclipse.xtext.linking.ILinker;
import org.eclipse.xtext.linking.impl.Linker;
import org.eclipse.xtext.scoping.impl.ImportUriResolver;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ATestRuntimeModule extends org.eclipse.amp.amf.testing.AbstractATestRuntimeModule {

    public Class<? extends ImportUriResolver> bindImportUriResolver() {
        return ATestImportResolver.class;
    }

    @Override
    /**
     * @return
     * @see org.eclipse.xtext.service.DefaultRuntimeModule#bindILinker()
     */
    public Class<? extends ILinker> bindILinker() {
        return Linker.class;
    }

    // /**
    // * @return
    // * @see org.eclipse.xtext.service.DefaultRuntimeModule#bindIValueConverterService()
    // */
    // public Class<? extends IValueConverterService> bindIValueConverterService() {
    // return AMPTerminalConverters.class;
    // }
}

