grammar org.eclipse.amp.amf.testing.ATest with org.eclipse.amp.amf.abase.ABase

generate aTest "http://www.eclipse.org/amp/amf/testing/ATest"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://www.eclipse.org/amp/amf/abase/ABase"
import "platform:/resource/org.eclipse.amp.amf.acore/src/model/metaabm.ecore"

Model :
	{Model} (name=STRING)?
	(description=DESC_STRING)?
	((('tests' tests=Tests)? (contraints+=Constraint)+) |
	('contains' (contains+=TestMember)*))?;

Tests :
	importURI=STRING;

TestMember :
	importURI=STRING;

Constraint :
	measure=Measure "(" agent=[SAgent|ID] "." attribute=[SAttribute|ID] ("=" qualifier=[SStateValue|ID])? ")" ("=" "[" minValue=Value "," maxValue=Value "]");

enum Measure :
	COUNT = "Count" | AVERAGE = "Average" | SUM = "Sum" | MINIMUM = "Minimum" | MAXIMUM = "Maximum";

