/*
 * generated by Xtext
 */
package org.eclipse.amp.amf.parameters.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AParUiModule extends org.eclipse.amp.amf.parameters.ui.AbstractAParUiModule {
	public AParUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
