/*
 * generated by Xtext
 */
package org.eclipse.amp.amf.abase.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ABaseUiModule extends org.eclipse.amp.amf.abase.ui.AbstractABaseUiModule {
	public ABaseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
