/*
 * generated by Xtext
 */
package org.eclipse.amp.amf.testing.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ATestUiModule extends org.eclipse.amp.amf.testing.ui.AbstractATestUiModule {
	public ATestUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
